# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
# Container registry service connection established during pipeline creation
dockerRegistryServiceConnection: 'cc2a8a0d-22bb-4c65-921f-aa3606c1afcb'
imageRepository: 'adarshmishraazurepipelineslearningactivity'
containerRegistry: 'dccloudacr.azurecr.io'
dockerfilePath: '$(Build.SourcesDirectory)/AzurePipelines/Dockerfile'
tag: '$(Build.BuildId)'

pool:
name: 'devops-vm'

stages:
- stage: Build
displayName: Build
jobs:
- job: Build
displayName: Build
steps:
- task: Docker@2
displayName: Build the image
inputs:
containerRegistry: '$(dockerRegistryServiceConnection)'
repository: '$(imageRepository)'
command: 'build'
Dockerfile: '**/Dockerfile'
tags: '$(tag)'
- stage: Push
displayName: Push
jobs:
- job: Push
displayName: Push
steps:
- task: Docker@2
displayName: Push image to azure container registry
inputs:
containerRegistry: '$(dockerRegistryServiceConnection)'
repository: '$(imageRepository)'
command: 'push'
tags: '$(tag)'
- stage: Deploy
displayName: Deploy to Azure Web App
jobs:
- job: Deploy
displayName: Deploy to Azure Web App
steps:
- task: AzureWebAppContainer@1
displayName: Deploy Latest Image to Azure Web App
inputs:
azureSubscription: 'Azure for Students(47642c4b-8b7e-4191-bf57-39569d20ebde)'
appName: 'aa-webapp'
containers: '$(containerRegistry)/$(imageRepository):$(tag)'